export const projects = [
  {
    title: "E-Commerce Platform",
    description: "Full-stack Next.js commerce solution with Stripe integration.",
    slug: "e-commerce-platform",
    tag: "Full Stack",
    tech: ["Next.js", "Node.js", "MongoDB", "Stripe"],
    content: "This project includes product listing, cart system, authentication, and secure payments with Stripe. It features a responsive UI and efficient state management.",
  },
  {
    title: "AI Image Generator",
    description: "Generate high-quality images using OpenAI API.",
    slug: "ai-image-generator",
    tag: "AI",
    tech: ["React", "OpenAI API", "Node.js"],
    content: "Users can generate high-quality images from text prompts using AI models with real-time preview and historical image storage.",
  },
  {
    title: "Portfolio Website",
    description: "Modern animated portfolio using Framer Motion.",
    slug: "portfolio-website",
    tag: "Frontend",
    tech: ["Next.js", "Tailwind", "Framer Motion"],
    content: "A sleek, modern portfolio featuring smooth animations, responsive design, and dynamic project showcase sections.",
  },
  {
    title: "Real-time Chat App",
    description: "Chat application using Socket.io and Redis.",
    slug: "chat-app",
    tag: "Realtime",
    tech: ["Node.js", "Socket.io", "Redis"],
    content: "A real-time messaging system with instant updates, online status indicators, and reliable message delivery using Redis.",
  },
  {
    title: "SaaS Dashboard",
    description: "Analytics dashboard with authentication & payments.",
    slug: "saas-dashboard",
    tag: "SaaS",
    tech: ["Next.js", "Stripe", "PostgreSQL"],
    content: "Comprehensive SaaS dashboard with user authentication, subscription billing via Stripe, and detailed analytics visualization.",
  },
  {
    title: "Task Manager API",
    description: "REST API built with Node.js and MongoDB.",
    slug: "task-manager",
    tag: "Backend",
    tech: ["Node.js", "Express", "MongoDB"],
    content: "Secure and scalable RESTful API for task management with JWT authentication and full CRUD operations.",
  },
  {
    title: "Social Media App",
    description: "Full-stack app with posts, likes, and comments.",
    slug: "social-app",
    tag: "Full Stack",
    tech: ["React", "Node.js", "MongoDB"],
    content: "Social platform allowing users to create posts, interact through likes and comments, and follow other users.",
  },
  {
    title: "Dev Portfolio Builder",
    description: "Tool to generate developer portfolios dynamically.",
    slug: "portfolio-builder",
    tag: "Tool",
    tech: ["Next.js", "Tailwind", "AI"],
    content: "An AI-powered tool that helps developers generate professional portfolios by analyzing their GitHub and social profiles.",
  },
  {
    title: "Blog Platform",
    description: "Markdown-based blogging system with CMS.",
    slug: "blog-platform",
    tag: "CMS",
    tech: ["Next.js", "Markdown", "CMS"],
    content: "Blogging platform with Markdown support for easy content creation, integrated with a headless CMS for content management.",
  },
];
