export const projects = [
  {
    title: "LocalLM",
    description: "Privacy-focused frontend interface for local LLMs like Ollama and LM Studio.",
    slug: "locallm",
    tag: "AI / LLM",
    tech: ["Next.js", "Clerk", "Tailwind CSS 4", "Shadcn UI", "TypeScript", "ngrok"],
    content: "LocalLM is a modern Next.js-based web application designed as a frontend interface for local Large Language Models (LLMs). It provides direct integration with Ollama and LM Studio APIs, allowing users to run powerful AI models locally with complete privacy. The project features ngrok integration to securely tunnel local servers, enabling the hosted web interface to communicate with the local model and receive real-time responses. Features include secure authentication via Clerk, a modular chat interface with markdown support, and persistent state management for chat threads and model configurations.",
    github: "https://github.com/RishabhDubeyCS/locallm",
    live: "https://locallm-wheat.vercel.app/",
  },
  {
    title: "CORE_NODE (RESTful Chat API)",
    description: "High-performance Developer Terminal with RESTful architecture and CRUD management.",
    slug: "core-node",
    tag: "Full Stack",
    tech: ["Node.js", "Express.js", "MongoDB", "Mongoose", "EJS", "Bootstrap 5"],
    content: "CORE_NODE is a sophisticated Developer Terminal styled as a high-performance web application. It demonstrates a professional RESTful API architecture and full CRUD lifecycle management. Built with a 'Modern Midnight' theme, it features high-end physics-based animations, glassmorphism UI elements, and responsive fluidity across all devices. The backend utilizes Mongoose for schema-based validation and centralized error handling, ensuring robust data integrity and a seamless user experience.",
    github: "https://github.com/RishabhDubeyCS/Restful-chat-api",
    live: "https://restful-chat-api.vercel.app/",
  },
  {
    title: "Steam Talk",
    description: "Scalable real-time community platform for dynamic engagement.",
    slug: "steam-talk",
    tag: "Real-Time",
    tech: ["Next.js", "React", "Stream Chat", "Clerk", "Tailwind CSS", "Three.js", "Framer Motion"],
    content: "Built a scalable real-time web application for dynamic community engagement and live discussions by integrating Stream Chat APIs for channel-based messaging and real-time communication. Implemented secure authentication and authorization using Clerk with robust session management. Designed an immersive, high-performance user interface with interactive 3D visuals, animations, and responsive design to enhance user engagement. Developed dynamic routing and a modular component-based architecture using Next.js App Router to ensure scalability, maintainability, and clean code practices. Optimized application performance using efficient rendering techniques (SSR/CSR), improving load time, responsiveness, and overall user experience.",
    github: "https://github.com/RishabhDubeyCS/Steamtalk",
    live: "https://steamtalk.vercel.app/",
  },
  {
    title: "Next.js 16 Advanced Architecture",
    description: "Showcase of modular and scalable web application leveraging modern Next.js 16 App Router.",
    slug: "nextjs-learning-hub",
    tag: "Architecture",
    tech: ["Next.js 16", "React 19", "TypeScript", "Tailwind CSS", "shadcn/ui", "Radix UI"],
    content: "Architected a modular and scalable web application leveraging advanced Next.js 16 App Router architecture, including nested layouts, dynamic routing ([slug]), and well-structured code organization using private modules. Implemented hybrid rendering (Server and Client Components) to maximize performance, SEO, and bundle efficiency. Engineered a dynamic blog system using Static Site Generation (SSG) with robust loading and error boundaries to deliver a seamless user experience. Designed server-side search and filtering with URL-driven state management using modern Next.js navigation patterns. Developed RESTful API endpoints via Route Handlers to handle data fetching and backend logic efficiently. Built a responsive and accessible UI using Tailwind CSS and shadcn/ui, and optimized media delivery with the Next.js Image component to improve loading performance and user experience.",
    github: "https://github.com/RishabhDubeyCS/nextjs-playground",
    live: "https://nextjs-playground-psi-virid.vercel.app/",
  },
  {
    title: "Object Detection Dashboard",
    description: "Real-time AI application for object detection in the browser.",
    slug: "object-detection-dashboard",
    tag: "AI / ML",
    tech: ["React.js", "TensorFlow.js", "Coco-SSD", "WebGL", "HTML Canvas"],
    content: "Engineered a real-time object detection system using TensorFlow.js and Coco-SSD, enabling client-side ML inference in the browser. Implemented webcam-based multi-object detection with a canvas rendering pipeline for bounding boxes and confidence scores. Optimized performance using WebGL acceleration to achieve low-latency inference (~5 FPS), while applying filtering techniques to improve accuracy. Built a responsive UI with real-time updates and efficient state management, delivering a scalable, high-performance AI application.",
    github: "https://github.com/RishabhDubeyCS/react-tfjs-object-detector",
    live: "https://react-tfjs-object-detector.vercel.app/",
  },
  {
    title: "Razorpay Integration",
    description: "Seamless payment gateway integration using Razorpay API.",
    slug: "razorpay-integration",
    tag: "Full Stack",
    tech: ["React", "Node.js", "Express", "Razorpay API"],
    content: "Integrated Razorpay payment gateway into a MERN stack application, featuring order creation, secure checkout UI, and server-side payment verification for robust transaction handling.",
    github: "https://github.com/RishabhDubeyCS/Razorpay-Integration",
    live: "https://razorpay-integration-eosin.vercel.app/",
  },
  {
    title: "Wanderlust",
    description: "Full-stack travel accommodation listing application inspired by Airbnb.",
    slug: "wanderlust",
    tag: "Full Stack",
    tech: ["Node.js", "Express.js", "MongoDB", "Mongoose", "EJS", "Bootstrap"],
    content: "Wanderlust is a full-stack travel accommodation listing application inspired by Airbnb. It features comprehensive CRUD operations allowing users to browse, create, edit, and delete travel listings with detailed information like images, pricing, and location. Built with Node.js and Express, it utilizes MongoDB and Mongoose for robust data persistence. The frontend is rendered using EJS templates for dynamic content delivery, styled with Bootstrap for a responsive user experience. The application also implements specialized middleware for request processing, authentication, and error handling, ensuring a secure and scalable architecture.",
    github: "#",
    live: "#",
  },
  {
    title: "Portfolio Website",
    description: "Modern animated portfolio using Framer Motion.",
    slug: "portfolio-website",
    tag: "Frontend",
    tech: ["Next.js", "Tailwind", "Framer Motion"],
    content: "A sleek, modern portfolio featuring smooth animations, responsive design, and dynamic project showcase sections.",
    github: "https://github.com/RishabhDubeyCS/rishabh_portfolio-",
    live: "#",
  },
  {
    title: "AI Image Generator",
    description: "Generate high-quality images using OpenAI API.",
    slug: "ai-image-generator",
    tag: "AI",
    tech: ["React", "OpenAI API", "Node.js"],
    content: "Users can generate high-quality images from text prompts using AI models with real-time preview and historical image storage.",
    github: "#",
    live: "#",
  },
  {
    title: "E-Commerce Platform",
    description: "Full-stack Next.js commerce solution with Stripe integration.",
    slug: "e-commerce-platform",
    tag: "Full Stack",
    tech: ["Next.js", "Node.js", "MongoDB", "Stripe"],
    content: "This project includes product listing, cart system, authentication, and secure payments with Stripe. It features a responsive UI and efficient state management.",
    github: "#",
    live: "#",
  },
  {
    title: "SaaS Dashboard",
    description: "Analytics dashboard with authentication & payments.",
    slug: "saas-dashboard",
    tag: "SaaS",
    tech: ["Next.js", "Stripe", "PostgreSQL"],
    content: "Comprehensive SaaS dashboard with user authentication, subscription billing via Stripe, and detailed analytics visualization.",
    github: "#",
    live: "#",
  },
  {
    title: "Task Manager API",
    description: "REST API built with Node.js and MongoDB.",
    slug: "task-manager",
    tag: "Backend",
    tech: ["Node.js", "Express", "MongoDB"],
    content: "Secure and scalable RESTful API for task management with JWT authentication and full CRUD operations.",
    github: "#",
    live: "#",
  },
  {
    title: "Social Media App",
    description: "Full-stack app with posts, likes, and comments.",
    slug: "social-app",
    tag: "Full Stack",
    tech: ["React", "Node.js", "MongoDB"],
    content: "Social platform allowing users to create posts, interact through likes and comments, and follow other users.",
    github: "#",
    live: "#",
  },
  {
    title: "Modern Sidebar Navigation",
    description: "Responsive sidebar menu with modern UI and smooth animations.",
    slug: "modern-sidebar-navigation",
    tag: "Frontend",
    tech: [
      "HTML5",
      "CSS3",
      "Flexbox",
      "Animations",
      "Font Awesome",
      "Google Fonts",
    ],
    content:
      "A modern and responsive sidebar navigation UI built using pure HTML and CSS. Features a collapsible sidebar with smooth slide-in/out animations using the CSS checkbox hack, a full-screen hero section with background image, and interactive hover effects. Designed with a dark gradient theme and glassmorphism-inspired elements, making it ideal for portfolio or gallery websites.",
    github: "https://github.com/RishabhDubeyCS/Mini-Project-CSS",
    live: "#",
  },
  {
    title: "Weather App",
    description: "Modern weather forecast app with real-time data and clean UI.",
    slug: "weather-app",
    tag: "Frontend",
    tech: [
      "React 19",
      "Vite 7",
      "Material UI",
      "Framer Motion",
      "Tailwind CSS",
      "OpenWeatherMap API",
    ],
    content:
      "A modern weather forecasting application built using React and Vite that fetches real-time data from the OpenWeatherMap API. Users can search for any city to view temperature, min/max values, weather conditions, humidity, wind speed, and dynamic icons. The app features a clean and responsive UI using Material UI, enhanced with smooth animations via Framer Motion. Includes loading states, error handling for invalid inputs, and environment-based API configuration.",
    github: "https://github.com/RishabhDubeyCS/wheather-forcast/tree/main/mini-project",
    live: "#",
  },
  {
    title: "Simple To-Do App",
    description: "Clean and responsive task manager with smooth UI interactions.",
    slug: "simple-todo-app",
    tag: "Frontend",
    tech: [
      "HTML5",
      "CSS3",
      "JavaScript",
      "DOM Manipulation",
    ],
    content:
      "A simple and modern To-Do List application built using HTML, CSS, and JavaScript. Users can add and delete tasks with real-time updates and smooth animations. Designed with a clean, responsive UI to provide an intuitive task management experience while demonstrating core DOM manipulation concepts.",
    github: "https://github.com/RishabhDubeyCS/simple-todo-app#simple-todo-app",
    live: "#",
  }
];
