export const projects = [
  {
    title: "Wanderlust",
    description: "Full-stack travel accommodation listing application inspired by Airbnb.",
    slug: "wanderlust",
    tag: "Full Stack",
    tech: ["Node.js", "Express.js", "MongoDB", "Mongoose", "EJS", "Bootstrap"],
    content: "Wanderlust is a full-stack travel accommodation listing application inspired by Airbnb. It features comprehensive CRUD operations allowing users to browse, create, edit, and delete travel listings with detailed information like images, pricing, and location. Built with Node.js and Express, it utilizes MongoDB and Mongoose for robust data persistence. The frontend is rendered using EJS templates for dynamic content delivery, styled with Bootstrap for a responsive user experience. The application also implements specialized middleware for request processing, authentication, and error handling, ensuring a secure and scalable architecture.",
    github: "#",
    live: "#",
  },
  {
    title: "Steam Talk",
    description: "Scalable real-time community platform for dynamic engagement.",
    slug: "steam-talk",
    tag: "Real-Time",
    tech: ["Next.js", "React", "Stream Chat", "Clerk", "Tailwind CSS", "Three.js", "Framer Motion"],
    content: "Built a scalable real-time web application for dynamic community engagement and live discussions by integrating Stream Chat APIs for channel-based messaging and real-time communication. Implemented secure authentication and authorization using Clerk with robust session management. Designed an immersive, high-performance user interface with interactive 3D visuals, animations, and responsive design to enhance user engagement. Developed dynamic routing and a modular component-based architecture using Next.js App Router to ensure scalability, maintainability, and clean code practices. Optimized application performance using efficient rendering techniques (SSR/CSR), improving load time, responsiveness, and overall user experience.",
    github: "#",
    live: "#",
  },
  {
    title: "Next.js 16 Advanced Architecture",
    description: "Showcase of modular and scalable web application leveraging modern Next.js 16 App Router.",
    slug: "nextjs-learning-hub",
    tag: "Architecture",
    tech: ["Next.js 16", "React 19", "TypeScript", "Tailwind CSS", "shadcn/ui", "Radix UI"],
    content: "Architected a modular and scalable web application leveraging advanced Next.js 16 App Router architecture, including nested layouts, dynamic routing ([slug]), and well-structured code organization using private modules. Implemented hybrid rendering (Server and Client Components) to maximize performance, SEO, and bundle efficiency. Engineered a dynamic blog system using Static Site Generation (SSG) with robust loading and error boundaries to deliver a seamless user experience. Designed server-side search and filtering with URL-driven state management using modern Next.js navigation patterns. Developed RESTful API endpoints via Route Handlers to handle data fetching and backend logic efficiently. Built a responsive and accessible UI using Tailwind CSS and shadcn/ui, and optimized media delivery with the Next.js Image component to improve loading performance and user experience.",
    github: "#",
    live: "#",
  },
  {
    title: "Object Detection Dashboard",
    description: "Real-time AI application for object detection in the browser.",
    slug: "object-detection-dashboard",
    tag: "AI / ML",
    tech: ["React.js", "TensorFlow.js", "Coco-SSD", "WebGL", "HTML Canvas"],
    content: "Engineered a real-time object detection system using TensorFlow.js and Coco-SSD, enabling client-side ML inference in the browser. Implemented webcam-based multi-object detection with a canvas rendering pipeline for bounding boxes and confidence scores. Optimized performance using WebGL acceleration to achieve low-latency inference (~5 FPS), while applying filtering techniques to improve accuracy. Built a responsive UI with real-time updates and efficient state management, delivering a scalable, high-performance AI application.",
    github: "#",
    live: "#",
  },
  {
    title: "Mini-WhatsApp",
    description: "RESTful messaging application built with Node.js and MongoDB.",
    slug: "mini-whatsapp",
    tag: "Full Stack",
    tech: ["Node.js", "Express.js", "MongoDB", "Mongoose", "EJS", "Bootstrap"],
    content: "Developed a server-side messaging application using Node.js, Express, and MongoDB following RESTful API and CRUD architecture. Implemented RESTful routes (GET, POST, PATCH, DELETE) with Mongoose for efficient data modeling and database operations. Built a dynamic UI using EJS and Bootstrap with middleware support (method-override, centralized error handling). Applied MVC architecture and utilized Git/GitHub for version control and project management.",
    github: "#",
    live: "#",
  },
  {
    title: "Portfolio Website",
    description: "Modern animated portfolio using Framer Motion.",
    slug: "portfolio-website",
    tag: "Frontend",
    tech: ["Next.js", "Tailwind", "Framer Motion"],
    content: "A sleek, modern portfolio featuring smooth animations, responsive design, and dynamic project showcase sections.",
    github: "#",
    live: "#",
  },
  {
    title: "AI Image Generator",
    description: "Generate high-quality images using OpenAI API.",
    slug: "ai-image-generator",
    tag: "AI",
    tech: ["React", "OpenAI API", "Node.js"],
    content: "Users can generate high-quality images from text prompts using AI models with real-time preview and historical image storage.",
    github: "#",
    live: "#",
  },
  {
    title: "E-Commerce Platform",
    description: "Full-stack Next.js commerce solution with Stripe integration.",
    slug: "e-commerce-platform",
    tag: "Full Stack",
    tech: ["Next.js", "Node.js", "MongoDB", "Stripe"],
    content: "This project includes product listing, cart system, authentication, and secure payments with Stripe. It features a responsive UI and efficient state management.",
    github: "#",
    live: "#",
  },
  {
    title: "SaaS Dashboard",
    description: "Analytics dashboard with authentication & payments.",
    slug: "saas-dashboard",
    tag: "SaaS",
    tech: ["Next.js", "Stripe", "PostgreSQL"],
    content: "Comprehensive SaaS dashboard with user authentication, subscription billing via Stripe, and detailed analytics visualization.",
    github: "#",
    live: "#",
  },
  {
    title: "Task Manager API",
    description: "REST API built with Node.js and MongoDB.",
    slug: "task-manager",
    tag: "Backend",
    tech: ["Node.js", "Express", "MongoDB"],
    content: "Secure and scalable RESTful API for task management with JWT authentication and full CRUD operations.",
    github: "#",
    live: "#",
  },
  {
    title: "Real-time Chat App",
    description: "Chat application using Socket.io and Redis.",
    slug: "chat-app",
    tag: "Realtime",
    tech: ["Node.js", "Socket.io", "Redis"],
    content: "A real-time messaging system with instant updates, online status indicators, and reliable message delivery using Redis.",
    github: "#",
    live: "#",
  },
  {
    title: "Social Media App",
    description: "Full-stack app with posts, likes, and comments.",
    slug: "social-app",
    tag: "Full Stack",
    tech: ["React", "Node.js", "MongoDB"],
    content: "Social platform allowing users to create posts, interact through likes and comments, and follow other users.",
    github: "#",
    live: "#",
  },
  {
    title: "Dev Portfolio Builder",
    description: "Tool to generate developer portfolios dynamically.",
    slug: "portfolio-builder",
    tag: "Tool",
    tech: ["Next.js", "Tailwind", "AI"],
    content: "An AI-powered tool that helps developers generate professional portfolios by analyzing their GitHub and social profiles.",
    github: "#",
    live: "#",
  },
  {
    title: "Blog Platform",
    description: "Markdown-based blogging system with CMS.",
    slug: "blog-platform",
    tag: "CMS",
    tech: ["Next.js", "Markdown", "CMS"],
    content: "Blogging platform with Markdown support for easy content creation, integrated with a headless CMS for content management.",
    github: "#",
    live: "#",
  },
];
